import type { RecipeId, Resource, Terrain, TileFeature } from "./ids";

/**
 * A plant either produces goods or it produces an advantage. Depots, rail
 * yards, waste processors and power stations carry a buff instead of, or
 * beside, their output. The best buff on a network wins; they do not stack.
 */
export interface PlantBuff {
  /** Fraction off haulage quoted for this owner. */
  freightDiscount?: number;
  /** Multiplier on condition lost per tick by this owner's spans. */
  railDecayMultiplier?: number;
  /** Fraction off the cost of laying a new span. */
  railBuildDiscount?: number;
  /** Subtracted from audit exposure while the plant runs. */
  auditRelief?: number;
  /** Morale added per tick. */
  moraleLift?: number;
  /** Fraction of grid draw that cannot cause a blackout. One is immunity. */
  blackoutRelief?: number;
  /** Fraction of waste output avoided by every plant this owner runs. */
  wasteRelief?: number;
  /** Fraction off the power bill. */
  powerDiscount?: number;
  /** Fraction off any tariff charged on this owner's trades. */
  tariffRebate?: number;
  /** Multiplier on output of plants at the named tiers. */
  yieldByTier?: Partial<Record<number, number>>;
}

export interface Recipe {
  id: RecipeId;
  name: string;
  abbr: string;
  tier: 1 | 2 | 3 | 4 | 5 | 6;
  /** Plots this plant may be raised on. */
  terrains: Terrain[];
  /** Extra ground condition, such as a coastal plot for a port. */
  requiresFeature?: TileFeature;
  /** Extractors name the deposit they must sit on. */
  deposit?: Resource;
  input: Partial<Record<Resource, number>>;
  output: Partial<Record<Resource, number>>;
  /** Waste emitted beside the output. It lands in the owner's inventory. */
  waste?: Partial<Record<Resource, number>>;
  /** Grid draw per tick, bought at the board price for grid power. */
  power: number;
  /** Waste heat and particulate left on the plot each tick. */
  pollution: number;
  /** Workers on the payroll. Drives the wage bill. */
  crew: number;
  buildCost: number;
  /** Appraised value. Drives takeover thresholds and insurance. */
  baseValue: number;
  /** Precision plant. Smog on the plot wrecks its yield. */
  cleanRoom: boolean;
  buff?: PlantBuff;
  blurb: string;
  /** Thirty two pixel plant sprite key. */
  sprite: string;
}

export const RECIPES: Record<RecipeId, Recipe> = {
  NONE: {
    id: "NONE",
    name: "Vacant plot",
    abbr: "VACANT",
    tier: 1,
    terrains: [],
    input: {},
    output: {},
    power: 0,
    pollution: 0,
    crew: 0,
    buildCost: 0,
    baseValue: 0,
    cleanRoom: false,
    blurb: "Bare ground. Anyone holding the deed may build here.",
    sprite: "vacant_lot",
  },

  // Tier one. Extractors, tied to the deposit under the plot.
  OIL_DERRICK: {
    id: "OIL_DERRICK",
    name: "Oil derrick",
    abbr: "DERRICK",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "CRUDE_OIL",
    input: {},
    output: { CRUDE_OIL: 260 },
    power: 14,
    pollution: 1,
    crew: 30,
    buildCost: 260_000,
    baseValue: 520_000,
    cleanRoom: false,
    blurb: "A wooden tower over a hole, and a flare that never goes out.",
    sprite: "rig_derrick",
  },
  BAUXITE_MINE: {
    id: "BAUXITE_MINE",
    name: "Bauxite mine",
    abbr: "MINE",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "BAUXITE",
    input: {},
    output: { BAUXITE: 320 },
    waste: { TAILINGS: 14 },
    power: 16,
    pollution: 2,
    crew: 32,
    buildCost: 250_000,
    baseValue: 480_000,
    cleanRoom: false,
    blurb: "Red dust over everything downwind, and a road that eats tyres.",
    sprite: "rig_mine",
  },
  SILICA_QUARRY: {
    id: "SILICA_QUARRY",
    name: "Silica quarry",
    abbr: "QUARRY",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "SILICON_ORE",
    input: {},
    output: { SILICON_ORE: 190 },
    waste: { TAILINGS: 10 },
    power: 16,
    pollution: 2,
    crew: 28,
    buildCost: 250_000,
    baseValue: 500_000,
    cleanRoom: false,
    blurb: "Blasted benches and a crusher that runs two shifts.",
    sprite: "rig_quarry",
  },
  LITHIUM_FIELD: {
    id: "LITHIUM_FIELD",
    name: "Lithium brine field",
    abbr: "BRINE",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "LITHIUM",
    input: {},
    output: { LITHIUM: 88 },
    power: 22,
    pollution: 1,
    crew: 26,
    buildCost: 320_000,
    baseValue: 680_000,
    cleanRoom: false,
    blurb: "Rows of shallow pans left to the sun until the water is gone.",
    sprite: "rig_brine",
  },
  COAL_FACE: {
    id: "COAL_FACE",
    name: "Coal face",
    abbr: "COAL FACE",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "COAL",
    input: {},
    output: { COAL: 560 },
    waste: { FLUE_ASH: 12 },
    power: 20,
    pollution: 3,
    crew: 34,
    buildCost: 220_000,
    baseValue: 400_000,
    cleanRoom: false,
    blurb: "A seam, a cage and a shift that never sees daylight.",
    sprite: "rig_coal",
  },
  RARE_EARTH_DREDGE: {
    id: "RARE_EARTH_DREDGE",
    name: "Rare earth dredge",
    abbr: "DREDGE",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "RARE_EARTH",
    input: {},
    output: { RARE_EARTH: 52 },
    waste: { TAILINGS: 18, FLUE_ASH: 8 },
    power: 26,
    pollution: 4,
    crew: 30,
    buildCost: 480_000,
    baseValue: 1_100_000,
    cleanRoom: false,
    blurb: "Dredging the bottom for the seventeen metals everybody needs at once.",
    sprite: "rig_dredge",
  },
  IRON_MINE: {
    id: "IRON_MINE",
    name: "Iron mine",
    abbr: "IRON",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "IRON_ORE",
    input: {},
    output: { IRON_ORE: 420 },
    waste: { TAILINGS: 16 },
    power: 18,
    pollution: 2,
    crew: 32,
    buildCost: 240_000,
    baseValue: 430_000,
    cleanRoom: false,
    blurb: "Magnetite off the face, hauled to a steelworks or left in a heap.",
    sprite: "rig_mine",
  },
  COPPER_PIT: {
    id: "COPPER_PIT",
    name: "Copper pit",
    abbr: "PIT",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "COPPER_ORE",
    input: {},
    output: { COPPER_ORE: 150 },
    waste: { TAILINGS: 20 },
    power: 20,
    pollution: 3,
    crew: 30,
    buildCost: 280_000,
    baseValue: 560_000,
    cleanRoom: false,
    blurb: "An open pit that gets deeper every year and never quite closes.",
    sprite: "rig_pit",
  },
  SULFUR_WORKS: {
    id: "SULFUR_WORKS",
    name: "Sulfur works",
    abbr: "SULFUR",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "SULFUR",
    input: {},
    output: { SULFUR: 235 },
    waste: { FLUE_ASH: 10 },
    power: 18,
    pollution: 4,
    crew: 28,
    buildCost: 260_000,
    baseValue: 500_000,
    cleanRoom: false,
    blurb: "Yellow stacks and a smell that carries into the next township.",
    sprite: "rig_sulfur",
  },
  PHOSPHATE_STRIP: {
    id: "PHOSPHATE_STRIP",
    name: "Phosphate strip",
    abbr: "STRIP",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "PHOSPHATE",
    input: {},
    output: { PHOSPHATE: 265 },
    waste: { TAILINGS: 18 },
    power: 18,
    pollution: 3,
    crew: 30,
    buildCost: 250_000,
    baseValue: 470_000,
    cleanRoom: false,
    blurb: "Ground stripped, ground left, and crops grown on what comes off it.",
    sprite: "rig_strip",
  },
  URANIUM_SHAFT: {
    id: "URANIUM_SHAFT",
    name: "Uranium shaft",
    abbr: "SHAFT",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "URANIUM",
    input: {},
    output: { URANIUM: 34 },
    waste: { TAILINGS: 25 },
    power: 30,
    pollution: 2,
    crew: 40,
    buildCost: 520_000,
    baseValue: 1_200_000,
    cleanRoom: false,
    blurb: "Respirators, dosimeters and a payroll nobody talks about outside.",
    sprite: "rig_shaft",
  },
  TUNGSTEN_ADIT: {
    id: "TUNGSTEN_ADIT",
    name: "Tungsten adit",
    abbr: "ADIT",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "TUNGSTEN_ORE",
    input: {},
    output: { TUNGSTEN_ORE: 42 },
    waste: { TAILINGS: 14 },
    power: 26,
    pollution: 3,
    crew: 34,
    buildCost: 400_000,
    baseValue: 900_000,
    cleanRoom: false,
    blurb: "A horizontal shaft driven into the hillside for the hardest metal there is.",
    sprite: "rig_adit",
  },
  GRAPHITE_BANK: {
    id: "GRAPHITE_BANK",
    name: "Graphite bank",
    abbr: "GRAPHITE",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "GRAPHITE",
    input: {},
    output: { GRAPHITE: 122 },
    waste: { TAILINGS: 12 },
    power: 20,
    pollution: 3,
    crew: 30,
    buildCost: 280_000,
    baseValue: 540_000,
    cleanRoom: false,
    blurb: "Soft black seams cut out by hand where the machines cannot reach.",
    sprite: "rig_bank",
  },
  TIMBER_CAMP: {
    id: "TIMBER_CAMP",
    name: "Timber camp",
    abbr: "TIMBER",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "TIMBER",
    input: {},
    output: { TIMBER: 370 },
    power: 12,
    pollution: 1,
    crew: 30,
    buildCost: 200_000,
    baseValue: 380_000,
    cleanRoom: false,
    blurb: "Felled, bucked and floated down. The hillside does not grow back.",
    sprite: "rig_camp",
  },
  SALT_PAN: {
    id: "SALT_PAN",
    name: "Salt pan",
    abbr: "PAN",
    tier: 1,
    terrains: ["DEPOSIT"],
    deposit: "ROCK_SALT",
    input: {},
    output: { ROCK_SALT: 490 },
    power: 14,
    pollution: 1,
    crew: 24,
    buildCost: 190_000,
    baseValue: 360_000,
    cleanRoom: false,
    blurb: "White crust scraped off the flats and stacked into mountains.",
    sprite: "rig_pan",
  },

  // Tier two. Refineries.
  PETROCHEMICAL_PLANT: {
    id: "PETROCHEMICAL_PLANT",
    name: "Petrochemical plant",
    abbr: "PETROCHEM",
    tier: 2,
    terrains: ["REFINERY"],
    input: { CRUDE_OIL: 220, COAL: 250 },
    output: { POLYMER: 250 },
    waste: { FLUE_ASH: 15, TOXIC_SLAG: 8 },
    power: 55,
    pollution: 3,
    crew: 60,
    buildCost: 620_000,
    baseValue: 1_500_000,
    cleanRoom: false,
    blurb: "Crackers, columns and a flare visible from the far rim.",
    sprite: "plant_tower",
  },
  SMELTER: {
    id: "SMELTER",
    name: "Aluminium smelter",
    abbr: "SMELTER",
    tier: 2,
    terrains: ["REFINERY"],
    input: { BAUXITE: 300, COAL: 225 },
    output: { ALUMINUM: 140 },
    waste: { FLUE_ASH: 20 },
    power: 80,
    pollution: 4,
    crew: 62,
    buildCost: 700_000,
    baseValue: 1_600_000,
    cleanRoom: false,
    blurb: "Potlines that drink power all night and glow at the far end.",
    sprite: "plant_smelter",
  },
  STEELWORKS: {
    id: "STEELWORKS",
    name: "Steelworks",
    abbr: "STEEL",
    tier: 2,
    terrains: ["REFINERY"],
    input: { IRON_ORE: 380, COAL: 230 },
    output: { STEEL: 187 },
    waste: { FLUE_ASH: 22, TOXIC_SLAG: 10 },
    power: 75,
    pollution: 5,
    crew: 66,
    buildCost: 680_000,
    baseValue: 1_550_000,
    cleanRoom: false,
    blurb: "Blast furnaces, ladles and a shift change that stops the street.",
    sprite: "plant_smelter",
  },
  COPPER_SMELTER: {
    id: "COPPER_SMELTER",
    name: "Copper smelter",
    abbr: "CU SMELT",
    tier: 2,
    terrains: ["REFINERY"],
    input: { COPPER_ORE: 140, SULFUR: 95 },
    output: { COPPER: 107 },
    waste: { FLUE_ASH: 25, TOXIC_SLAG: 12 },
    power: 70,
    pollution: 6,
    crew: 60,
    buildCost: 660_000,
    baseValue: 1_500_000,
    cleanRoom: false,
    blurb: "Roasters and converters turning green rock into bright wire bar.",
    sprite: "plant_smelter",
  },
  ACID_PLANT: {
    id: "ACID_PLANT",
    name: "Sulfuric acid plant",
    abbr: "ACID",
    tier: 2,
    terrains: ["REFINERY"],
    input: { SULFUR: 210, ROCK_SALT: 220 },
    output: { SULFURIC_ACID: 214 },
    waste: { SPENT_ACID: 12 },
    power: 45,
    pollution: 4,
    crew: 50,
    buildCost: 580_000,
    baseValue: 1_300_000,
    cleanRoom: false,
    blurb: "Contact towers and a tank farm of the workhorse reagent.",
    sprite: "plant_tower",
  },
  LITHIUM_REFINERY: {
    id: "LITHIUM_REFINERY",
    name: "Lithium refinery",
    abbr: "LI PLANT",
    tier: 2,
    terrains: ["REFINERY"],
    input: { LITHIUM: 80, ROCK_SALT: 200 },
    output: { LITHIUM_CARBONATE: 65 },
    waste: { TAILINGS: 18 },
    power: 70,
    pollution: 3,
    crew: 58,
    buildCost: 720_000,
    baseValue: 1_700_000,
    cleanRoom: false,
    blurb: "Brine in, white powder out, and a mountain of wet waste behind.",
    sprite: "plant_pans",
  },
  RARE_EARTH_REFINERY: {
    id: "RARE_EARTH_REFINERY",
    name: "Rare earth refinery",
    abbr: "REE PLANT",
    tier: 2,
    terrains: ["REFINERY"],
    input: { RARE_EARTH: 34, SULFURIC_ACID: 75 },
    output: { RARE_EARTH_OXIDE: 50 },
    waste: { TOXIC_SLAG: 20, SPENT_ACID: 15 },
    power: 85,
    pollution: 5,
    crew: 64,
    buildCost: 880_000,
    baseValue: 2_100_000,
    cleanRoom: false,
    blurb: "Hundreds of stages of solvent extraction, and an inspector at the gate.",
    sprite: "plant_mill",
  },
  SILICA_KILN: {
    id: "SILICA_KILN",
    name: "Silica kiln",
    abbr: "KILN",
    tier: 2,
    terrains: ["REFINERY"],
    input: { SILICON_ORE: 155, COAL: 285 },
    output: { SILICA: 173 },
    waste: { FLUE_ASH: 14 },
    power: 65,
    pollution: 3,
    crew: 52,
    buildCost: 620_000,
    baseValue: 1_400_000,
    cleanRoom: false,
    blurb: "Washed, burned and graded until the sand is worth more than the ground.",
    sprite: "plant_kiln",
  },
  CEMENT_PLANT: {
    id: "CEMENT_PLANT",
    name: "Cement plant",
    abbr: "CEMENT",
    tier: 2,
    terrains: ["REFINERY"],
    input: { PHOSPHATE: 220, COAL: 283 },
    output: { CEMENT: 346 },
    waste: { FLUE_ASH: 30 },
    power: 60,
    pollution: 6,
    crew: 54,
    buildCost: 560_000,
    baseValue: 1_250_000,
    cleanRoom: false,
    blurb: "Rotary kilns throwing a plume that sets on the washing lines.",
    sprite: "plant_cement",
  },
  FERTILIZER_PLANT: {
    id: "FERTILIZER_PLANT",
    name: "Fertilizer plant",
    abbr: "FERT",
    tier: 2,
    terrains: ["REFINERY"],
    input: { PHOSPHATE: 200, SULFURIC_ACID: 62 },
    output: { FERTILIZER: 237 },
    waste: { SPENT_ACID: 18 },
    power: 55,
    pollution: 4,
    crew: 52,
    buildCost: 600_000,
    baseValue: 1_350_000,
    cleanRoom: false,
    blurb: "Granulation drums feeding every farm inside a hundred miles.",
    sprite: "plant_pans",
  },
  PULP_MILL: {
    id: "PULP_MILL",
    name: "Paper pulp mill",
    abbr: "PULP",
    tier: 2,
    terrains: ["REFINERY"],
    input: { TIMBER: 320, SULFURIC_ACID: 52 },
    output: { PAPER_PULP: 300 },
    waste: { SPENT_ACID: 20, FLUE_ASH: 10 },
    power: 50,
    pollution: 5,
    crew: 50,
    buildCost: 520_000,
    baseValue: 1_200_000,
    cleanRoom: false,
    blurb: "Digesters, and a river downstream that turns the colour of tea.",
    sprite: "plant_pulp",
  },
  URANIUM_MILL: {
    id: "URANIUM_MILL",
    name: "Uranium mill",
    abbr: "U MILL",
    tier: 2,
    terrains: ["REFINERY"],
    input: { URANIUM: 26, SULFURIC_ACID: 64 },
    output: { URANIUM_OXIDE: 31 },
    waste: { TAILINGS: 40 },
    power: 90,
    pollution: 4,
    crew: 60,
    buildCost: 950_000,
    baseValue: 2_400_000,
    cleanRoom: false,
    blurb: "Yellowcake in sealed drums and tailings ponds fenced both ways.",
    sprite: "plant_mill",
  },
  CARBIDE_WORKS: {
    id: "CARBIDE_WORKS",
    name: "Carbide works",
    abbr: "CARBIDE",
    tier: 2,
    terrains: ["REFINERY"],
    input: { TUNGSTEN_ORE: 36, COAL: 283 },
    output: { TUNGSTEN_CARBIDE: 24 },
    waste: { FLUE_ASH: 12 },
    power: 95,
    pollution: 5,
    crew: 56,
    buildCost: 900_000,
    baseValue: 2_200_000,
    cleanRoom: false,
    blurb: "Furnaces hot enough to make the hardest metal anybody has dug up.",
    sprite: "plant_kiln",
  },
  GRAPHITE_WORKS: {
    id: "GRAPHITE_WORKS",
    name: "Graphite works",
    abbr: "GRAPH WORKS",
    tier: 2,
    terrains: ["REFINERY"],
    input: { GRAPHITE: 110, POLYMER: 57 },
    output: { SYNTHETIC_GRAPHITE: 94 },
    waste: { FLUE_ASH: 18 },
    power: 70,
    pollution: 4,
    crew: 54,
    buildCost: 680_000,
    baseValue: 1_600_000,
    cleanRoom: false,
    blurb: "Baked electrodes and anode stock for every furnace on the board.",
    sprite: "plant_kiln",
  },
  FUEL_REFINERY: {
    id: "FUEL_REFINERY",
    name: "Fuel refinery",
    abbr: "FUEL",
    tier: 2,
    terrains: ["REFINERY"],
    input: { CRUDE_OIL: 200, COAL: 300 },
    output: { FUEL_OIL: 321 },
    waste: { FLUE_ASH: 20, TOXIC_SLAG: 10 },
    power: 65,
    pollution: 4,
    crew: 56,
    buildCost: 640_000,
    baseValue: 1_500_000,
    cleanRoom: false,
    blurb: "The heavy cut, sold to anyone burning under a boiler.",
    sprite: "plant_tower",
  },

  // Tier three. Components, and the utilities that keep them running.
  SEMICONDUCTOR_FAB: {
    id: "SEMICONDUCTOR_FAB",
    name: "Semiconductor fab",
    abbr: "FAB",
    tier: 3,
    terrains: ["WORKS"],
    input: { SILICA: 130, POLYMER: 170, RARE_EARTH_OXIDE: 30 },
    output: { MICROCHIP: 150 },
    waste: { SPENT_ACID: 25, FLUE_ASH: 5 },
    power: 150,
    pollution: 1,
    crew: 110,
    buildCost: 1_800_000,
    baseValue: 3_400_000,
    cleanRoom: true,
    blurb: "A clean room with its own weather. One speck of ash ruins a shift.",
    sprite: "plant_fab",
  },
  CIRCUIT_WORKS: {
    id: "CIRCUIT_WORKS",
    name: "Circuit works",
    abbr: "CIRCUIT",
    tier: 3,
    terrains: ["WORKS"],
    input: { MICROCHIP: 90, COPPER: 30 },
    output: { CIRCUIT_BOARD: 84 },
    waste: { SPENT_ACID: 20 },
    power: 120,
    pollution: 1,
    crew: 100,
    buildCost: 2_200_000,
    baseValue: 4_200_000,
    cleanRoom: true,
    blurb: "Chips placed, soldered and tested under a microscope.",
    sprite: "plant_line",
  },
  BATTERY_PLANT: {
    id: "BATTERY_PLANT",
    name: "Battery plant",
    abbr: "BATTERY",
    tier: 3,
    terrains: ["WORKS"],
    input: { LITHIUM_CARBONATE: 60, ALUMINUM: 100, POLYMER: 110 },
    output: { BATTERY: 96 },
    waste: { SPENT_ACID: 30, TOXIC_SLAG: 12 },
    power: 110,
    pollution: 2,
    crew: 105,
    buildCost: 1_900_000,
    baseValue: 3_600_000,
    cleanRoom: false,
    blurb: "Cells wound, filled and stacked. The fire brigade knows the address.",
    sprite: "plant_line",
  },
  WIRE_MILL: {
    id: "WIRE_MILL",
    name: "Wire mill",
    abbr: "WIRE",
    tier: 3,
    terrains: ["WORKS"],
    input: { COPPER: 130, POLYMER: 210 },
    output: { COPPER_WIRE: 173 },
    waste: { TOXIC_SLAG: 10 },
    power: 90,
    pollution: 3,
    crew: 90,
    buildCost: 1_500_000,
    baseValue: 2_900_000,
    cleanRoom: false,
    blurb: "Drawn down to gauge and coated, spooled onto drums the size of a cart.",
    sprite: "plant_line",
  },
  PLATE_ROLLING: {
    id: "PLATE_ROLLING",
    name: "Plate rolling mill",
    abbr: "PLATE",
    tier: 3,
    terrains: ["WORKS"],
    input: { STEEL: 330, TUNGSTEN_CARBIDE: 7 },
    output: { STEEL_PLATE: 217 },
    waste: { FLUE_ASH: 12 },
    power: 100,
    pollution: 4,
    crew: 95,
    buildCost: 1_600_000,
    baseValue: 3_100_000,
    cleanRoom: false,
    blurb: "Ingots passed back and forth until they are flat and certified.",
    sprite: "plant_shop",
  },
  GLASS_WORKS: {
    id: "GLASS_WORKS",
    name: "Glass works",
    abbr: "GLASS",
    tier: 3,
    terrains: ["WORKS"],
    input: { SILICA: 300, SULFURIC_ACID: 71 },
    output: { GLASS_PANEL: 249 },
    waste: { SPENT_ACID: 24, FLUE_ASH: 8 },
    power: 120,
    pollution: 2,
    crew: 100,
    buildCost: 1_700_000,
    baseValue: 3_200_000,
    cleanRoom: false,
    blurb: "Float lines running a ribbon of glass that never stops moving.",
    sprite: "plant_shop",
  },
  MAGNET_WORKS: {
    id: "MAGNET_WORKS",
    name: "Magnet works",
    abbr: "MAGNET",
    tier: 3,
    terrains: ["WORKS"],
    input: { RARE_EARTH_OXIDE: 85, STEEL: 70 },
    output: { MAGNET: 108 },
    waste: { TOXIC_SLAG: 15, SPENT_ACID: 12 },
    power: 105,
    pollution: 3,
    crew: 98,
    buildCost: 1_900_000,
    baseValue: 3_500_000,
    cleanRoom: false,
    blurb: "Pressed in a field, sintered, plated and kept off the steel benches.",
    sprite: "plant_shop",
  },
  TURBINE_WORKS: {
    id: "TURBINE_WORKS",
    name: "Turbine works",
    abbr: "BLADES",
    tier: 3,
    terrains: ["WORKS"],
    input: { TUNGSTEN_CARBIDE: 12, STEEL_PLATE: 113 },
    output: { TURBINE_BLADE: 40 },
    power: 140,
    pollution: 3,
    crew: 108,
    buildCost: 2_100_000,
    baseValue: 3_900_000,
    cleanRoom: true,
    blurb: "Cast, coated and balanced to a tolerance measured in microns.",
    sprite: "plant_shop",
  },
  COMPOSITE_WORKS: {
    id: "COMPOSITE_WORKS",
    name: "Composite works",
    abbr: "COMPOSITE",
    tier: 3,
    terrains: ["WORKS"],
    input: { POLYMER: 320, SYNTHETIC_GRAPHITE: 73 },
    output: { COMPOSITE_PANEL: 64 },
    waste: { TOXIC_SLAG: 18 },
    power: 115,
    pollution: 4,
    crew: 100,
    buildCost: 1_800_000,
    baseValue: 3_300_000,
    cleanRoom: false,
    blurb: "Layers laid by hand, bagged and cured in an autoclave.",
    sprite: "plant_line",
  },
  BEARING_SHOP: {
    id: "BEARING_SHOP",
    name: "Bearing shop",
    abbr: "BEARINGS",
    tier: 3,
    terrains: ["WORKS"],
    input: { STEEL: 300, TUNGSTEN_CARBIDE: 11 },
    output: { BEARING: 128 },
    waste: { FLUE_ASH: 10 },
    power: 95,
    pollution: 2,
    crew: 92,
    buildCost: 1_600_000,
    baseValue: 3_000_000,
    cleanRoom: false,
    blurb: "Ground to a ten thousandth of an inch and packed in grease.",
    sprite: "plant_shop",
  },
  FUEL_FABRICATION: {
    id: "FUEL_FABRICATION",
    name: "Fuel fabrication plant",
    abbr: "FUEL FAB",
    tier: 3,
    terrains: ["WORKS"],
    input: { URANIUM_OXIDE: 15, STEEL_PLATE: 115 },
    output: { REACTOR_FUEL: 20 },
    waste: { TAILINGS: 30 },
    power: 130,
    pollution: 2,
    crew: 110,
    buildCost: 2_400_000,
    baseValue: 4_600_000,
    cleanRoom: true,
    blurb: "Cladding tubes, glove boxes and a count kept in a locked book.",
    sprite: "plant_fab",
  },
  CATALYST_REFINERY: {
    id: "CATALYST_REFINERY",
    name: "Catalyst refinery",
    abbr: "CATALYST",
    tier: 3,
    terrains: ["WORKS"],
    input: { RARE_EARTH_OXIDE: 25, SULFURIC_ACID: 336 },
    output: { CATALYST: 56 },
    waste: { SPENT_ACID: 40, TOXIC_SLAG: 12 },
    power: 120,
    pollution: 4,
    crew: 100,
    buildCost: 1_900_000,
    baseValue: 3_600_000,
    cleanRoom: false,
    blurb: "Platinum on ceramic honeycomb. Expensive, and it never gets used up.",
    sprite: "plant_tank",
  },
  HYDRAULIC_SHOP: {
    id: "HYDRAULIC_SHOP",
    name: "Hydraulic shop",
    abbr: "HYDRAULICS",
    tier: 3,
    terrains: ["WORKS"],
    input: { BEARING: 36, COPPER_WIRE: 68 },
    output: { HYDRAULIC_UNIT: 73 },
    power: 110,
    pollution: 3,
    crew: 100,
    buildCost: 1_800_000,
    baseValue: 3_400_000,
    cleanRoom: false,
    blurb: "Pumps, rams and valves rated to move a mountain one stroke at a time.",
    sprite: "plant_shop",
  },
  OPTICS_WORKS: {
    id: "OPTICS_WORKS",
    name: "Optics works",
    abbr: "OPTICS",
    tier: 3,
    terrains: ["WORKS"],
    input: { GLASS_PANEL: 140, RARE_EARTH_OXIDE: 18 },
    output: { PRECISION_OPTICS: 43 },
    power: 125,
    pollution: 1,
    crew: 104,
    buildCost: 2_300_000,
    baseValue: 4_400_000,
    cleanRoom: true,
    blurb: "Ground and polished to fractions of a wavelength, then packed in foam.",
    sprite: "plant_fab",
  },
  SOLVENT_PLANT: {
    id: "SOLVENT_PLANT",
    name: "Solvent plant",
    abbr: "SOLVENT",
    tier: 3,
    terrains: ["WORKS"],
    input: { FUEL_OIL: 400, SULFURIC_ACID: 170 },
    output: { SOLVENT: 312 },
    waste: { SPENT_ACID: 35 },
    power: 85,
    pollution: 3,
    crew: 88,
    buildCost: 1_400_000,
    baseValue: 2_700_000,
    cleanRoom: false,
    blurb: "Distilled clean enough to wash a reactor and cheap enough to spill.",
    sprite: "plant_tank",
  },

  POWER_STATION: {
    id: "POWER_STATION",
    name: "Power station",
    abbr: "POWER",
    tier: 3,
    terrains: ["WORKS"],
    input: { COAL: 1_200, FUEL_OIL: 300 },
    output: { POWER: 2_500 },
    waste: { FLUE_ASH: 60 },
    power: 40,
    pollution: 8,
    crew: 90,
    buildCost: 1_800_000,
    baseValue: 3_500_000,
    cleanRoom: false,
    buff: { blackoutRelief: 0.5 },
    blurb: "Boilers, turbines and a chimney you can see from the crown jewel.",
    sprite: "plant_power",
  },
  WASTE_PROCESSOR: {
    id: "WASTE_PROCESSOR",
    name: "Waste processor",
    abbr: "WASTE",
    tier: 3,
    terrains: ["WORKS"],
    input: { TOXIC_SLAG: 60, FLUE_ASH: 60, TAILINGS: 60 },
    output: { CEMENT: 300, RARE_EARTH_OXIDE: 60 },
    power: 130,
    pollution: 3,
    crew: 90,
    buildCost: 2_000_000,
    baseValue: 3_800_000,
    cleanRoom: false,
    buff: { wasteRelief: 0.5 },
    blurb: "Classifies, leaches and recovers. It eats what the rest of the board spills.",
    sprite: "plant_waste",
  },
  ACID_RECOVERY: {
    id: "ACID_RECOVERY",
    name: "Acid recovery works",
    abbr: "ACID REC",
    tier: 3,
    terrains: ["WORKS"],
    input: { SPENT_ACID: 120, ROCK_SALT: 200 },
    output: { SULFURIC_ACID: 380 },
    waste: { TOXIC_SLAG: 10 },
    power: 70,
    pollution: 4,
    crew: 70,
    buildCost: 1_300_000,
    baseValue: 2_500_000,
    cleanRoom: false,
    buff: { wasteRelief: 0.25 },
    blurb: "Strips exhausted liquor back to reagent and sells it to the next plant.",
    sprite: "plant_tank",
  },
  FREIGHT_DEPOT: {
    id: "FREIGHT_DEPOT",
    name: "Freight depot",
    abbr: "DEPOT",
    tier: 3,
    terrains: ["WORKS"],
    input: {},
    output: {},
    power: 25,
    pollution: 1,
    crew: 40,
    buildCost: 900_000,
    baseValue: 1_600_000,
    cleanRoom: false,
    buff: { freightDiscount: 0.35 },
    blurb: "Sidings, cranes and a yard. Haulage across your own ground costs less.",
    sprite: "plant_depot",
  },
  RAIL_YARD: {
    id: "RAIL_YARD",
    name: "Rail yard",
    abbr: "RAIL YARD",
    tier: 3,
    terrains: ["WORKS"],
    input: {},
    output: {},
    power: 30,
    pollution: 1,
    crew: 45,
    buildCost: 1_100_000,
    baseValue: 2_000_000,
    cleanRoom: false,
    buff: { railDecayMultiplier: 0.4, railBuildDiscount: 0.3 },
    blurb: "Shops, turntables and spare rail. Your spans wear out slower and cost less.",
    sprite: "plant_yard",
  },

  // Tier four. Devices.
  NEURAL_ENGINE_LAB: {
    id: "NEURAL_ENGINE_LAB",
    name: "Neural engine lab",
    abbr: "NEURAL LAB",
    tier: 4,
    terrains: ["ADVANCED"],
    input: { MICROCHIP: 180, CIRCUIT_BOARD: 60, MAGNET: 75 },
    output: { NEURAL_CORE: 84 },
    waste: { SPENT_ACID: 40 },
    power: 300,
    pollution: 1,
    crew: 180,
    buildCost: 4_200_000,
    baseValue: 8_000_000,
    cleanRoom: true,
    blurb: "Silicon that learns. The lab claims it thinks, and the market agrees.",
    sprite: "plant_lab",
  },
  ROBOTICS_ASSEMBLY: {
    id: "ROBOTICS_ASSEMBLY",
    name: "Robotics assembly",
    abbr: "ROBOTICS",
    tier: 4,
    terrains: ["ADVANCED"],
    input: { MICROCHIP: 150, HYDRAULIC_UNIT: 90, BEARING: 45 },
    output: { ROBOTIC_UNIT: 158 },
    waste: { FLUE_ASH: 15 },
    power: 280,
    pollution: 1,
    crew: 175,
    buildCost: 3_600_000,
    baseValue: 6_800_000,
    cleanRoom: false,
    blurb: "Arms and frames moving down a line that is mostly machines itself.",
    sprite: "plant_robot",
  },
  SATELLITE_WORKS: {
    id: "SATELLITE_WORKS",
    name: "Satellite works",
    abbr: "SATELLITES",
    tier: 4,
    terrains: ["ADVANCED"],
    input: { CIRCUIT_BOARD: 120, PRECISION_OPTICS: 40, COMPOSITE_PANEL: 30 },
    output: { SATELLITE: 36 },
    power: 320,
    pollution: 1,
    crew: 190,
    buildCost: 5_400_000,
    baseValue: 10_000_000,
    cleanRoom: true,
    blurb: "Clean rooms, shakers and a launch contract nobody else can sign.",
    sprite: "plant_satellite",
  },
  TURBINE_PLANT: {
    id: "TURBINE_PLANT",
    name: "Turbine plant",
    abbr: "TURBINES",
    tier: 4,
    terrains: ["ADVANCED"],
    input: { TURBINE_BLADE: 90, BEARING: 60 },
    output: { GAS_TURBINE: 53 },
    waste: { FLUE_ASH: 12 },
    power: 260,
    pollution: 2,
    crew: 170,
    buildCost: 4_600_000,
    baseValue: 8_600_000,
    cleanRoom: false,
    blurb: "A jet engine bolted to a generator and shipped where the grid refuses to go.",
    sprite: "plant_yard",
  },
  TRANSFORMER_WORKS: {
    id: "TRANSFORMER_WORKS",
    name: "Transformer works",
    abbr: "TRANSFORM",
    tier: 4,
    terrains: ["ADVANCED"],
    input: { COPPER_WIRE: 300, STEEL_PLATE: 145, MAGNET: 25 },
    output: { POWER_TRANSFORMER: 93 },
    waste: { FLUE_ASH: 10 },
    power: 240,
    pollution: 2,
    crew: 165,
    buildCost: 4_000_000,
    baseValue: 7_600_000,
    cleanRoom: false,
    blurb: "Copper and oil in a steel tank, tested at twice the rated voltage.",
    sprite: "plant_transformer",
  },
  HAULER_PLANT: {
    id: "HAULER_PLANT",
    name: "Hauler plant",
    abbr: "HAULERS",
    tier: 4,
    terrains: ["ADVANCED"],
    input: { BEARING: 120, STEEL_PLATE: 250, HYDRAULIC_UNIT: 40 },
    output: { HEAVY_HAULER: 64 },
    waste: { FLUE_ASH: 18 },
    power: 220,
    pollution: 3,
    crew: 170,
    buildCost: 3_800_000,
    baseValue: 7_200_000,
    cleanRoom: false,
    blurb: "Diesel trucks rated for the pit road and built to be repaired in the field.",
    sprite: "plant_hauler",
  },
  REACTOR_WORKS: {
    id: "REACTOR_WORKS",
    name: "Reactor works",
    abbr: "REACTORS",
    tier: 4,
    terrains: ["ADVANCED"],
    input: { REACTOR_FUEL: 30, STEEL_PLATE: 180, CATALYST: 20 },
    output: { CHEMICAL_REACTOR: 44 },
    waste: { TAILINGS: 25 },
    power: 300,
    pollution: 3,
    crew: 185,
    buildCost: 5_200_000,
    baseValue: 9_800_000,
    cleanRoom: false,
    blurb: "Jacketed vessels with agitation and relief, welded by certified hands only.",
    sprite: "plant_reactor",
  },
  SENSOR_WORKS: {
    id: "SENSOR_WORKS",
    name: "Sensor works",
    abbr: "SENSORS",
    tier: 4,
    terrains: ["ADVANCED"],
    input: { MICROCHIP: 300, PRECISION_OPTICS: 25 },
    output: { SENSOR_ARRAY: 110 },
    power: 200,
    pollution: 1,
    crew: 160,
    buildCost: 3_400_000,
    baseValue: 6_400_000,
    cleanRoom: true,
    blurb: "Every gauge and camera that reports to somebody standing far away.",
    sprite: "plant_lab",
  },
  ISOTOPE_PLANT: {
    id: "ISOTOPE_PLANT",
    name: "Isotope plant",
    abbr: "ISOTOPES",
    tier: 4,
    terrains: ["ADVANCED"],
    input: { REACTOR_FUEL: 40, CATALYST: 30 },
    output: { MEDICAL_ISOTOPE: 28 },
    waste: { TAILINGS: 20 },
    power: 280,
    pollution: 2,
    crew: 175,
    buildCost: 5_600_000,
    baseValue: 10_500_000,
    cleanRoom: false,
    blurb: "Short lived isotopes flown out to hospitals before they decay.",
    sprite: "plant_reactor",
  },
  PHARMA_WORKS: {
    id: "PHARMA_WORKS",
    name: "Pharma works",
    abbr: "PHARMA",
    tier: 4,
    terrains: ["ADVANCED"],
    input: { SOLVENT: 600, CATALYST: 40 },
    output: { SYNTHETIC_DRUG: 57 },
    waste: { SPENT_ACID: 60 },
    power: 250,
    pollution: 3,
    crew: 180,
    buildCost: 4_400_000,
    baseValue: 8_400_000,
    cleanRoom: true,
    blurb: "Reactors under pressure, then sterile filling and a brand name.",
    sprite: "plant_pharma",
  },
  FUEL_CELL_WORKS: {
    id: "FUEL_CELL_WORKS",
    name: "Fuel cell works",
    abbr: "FUEL CELLS",
    tier: 4,
    terrains: ["ADVANCED"],
    input: { MAGNET: 60, CATALYST: 60, COMPOSITE_PANEL: 65 },
    output: { FUEL_CELL: 41 },
    power: 230,
    pollution: 2,
    crew: 170,
    buildCost: 4_800_000,
    baseValue: 9_000_000,
    cleanRoom: false,
    blurb: "Hydrogen in, power out, water as the only exhaust. Quiet and costly.",
    sprite: "plant_line",
  },
  SUPERCONDUCTOR_MILL: {
    id: "SUPERCONDUCTOR_MILL",
    name: "Superconductor mill",
    abbr: "SUPERCOND",
    tier: 4,
    terrains: ["ADVANCED"],
    input: { RARE_EARTH_OXIDE: 200, PRECISION_OPTICS: 30, CATALYST: 25 },
    output: { SUPERCONDUCTOR: 24 },
    power: 350,
    pollution: 2,
    crew: 190,
    buildCost: 6_000_000,
    baseValue: 11_500_000,
    cleanRoom: true,
    blurb: "Wire that carries current with no losses, provided you keep it cold.",
    sprite: "plant_fab",
  },

  // Tier five. Systems.
  COMPUTE_CAMPUS: {
    id: "COMPUTE_CAMPUS",
    name: "Compute campus",
    abbr: "COMPUTE",
    tier: 5,
    terrains: ["CAMPUS"],
    input: { NEURAL_CORE: 160, SUPERCONDUCTOR: 15 },
    output: { COMPUTE_CLUSTER: 38 },
    power: 1_200,
    pollution: 2,
    crew: 300,
    buildCost: 14_000_000,
    baseValue: 28_000_000,
    cleanRoom: false,
    blurb: "Halls of neural cores with the cooling to match. A mill for thinking.",
    sprite: "plant_compute",
  },
  FLEET_YARD: {
    id: "FLEET_YARD",
    name: "Autonomous fleet yard",
    abbr: "FLEET",
    tier: 5,
    terrains: ["CAMPUS"],
    input: { ROBOTIC_UNIT: 300, HEAVY_HAULER: 45, SENSOR_ARRAY: 35 },
    output: { AUTONOMOUS_FLEET: 33 },
    power: 1_000,
    pollution: 2,
    crew: 290,
    buildCost: 13_000_000,
    baseValue: 26_000_000,
    cleanRoom: false,
    buff: { freightDiscount: 0.25 },
    blurb: "Driverless haulage running the pit road around the clock and never tiring.",
    sprite: "plant_gigafactory",
  },
  ORBITAL_WORKS: {
    id: "ORBITAL_WORKS",
    name: "Orbital works",
    abbr: "ORBITAL",
    tier: 5,
    terrains: ["CAMPUS"],
    input: { SATELLITE: 80, SENSOR_ARRAY: 80, FUEL_CELL: 35 },
    output: { ORBITAL_NETWORK: 31 },
    power: 1_400,
    pollution: 1,
    crew: 320,
    buildCost: 18_000_000,
    baseValue: 34_000_000,
    cleanRoom: false,
    blurb: "Constellations enough to cover every acre of the board at once.",
    sprite: "plant_launch",
  },
  FUSION_LAB: {
    id: "FUSION_LAB",
    name: "Fusion lab",
    abbr: "FUSION",
    tier: 5,
    terrains: ["CAMPUS"],
    input: { REACTOR_FUEL: 180, POWER_TRANSFORMER: 60, SUPERCONDUCTOR: 30 },
    output: { FUSION_REACTOR: 21 },
    power: 1_800,
    pollution: 2,
    crew: 340,
    buildCost: 26_000_000,
    baseValue: 48_000_000,
    cleanRoom: false,
    buff: { blackoutRelief: 1 },
    blurb: "A star in a bottle, if the bottle holds. Every rival wants the drawings.",
    sprite: "plant_reactor",
  },
  GRID_WORKS: {
    id: "GRID_WORKS",
    name: "Grid works",
    abbr: "GRID",
    tier: 5,
    terrains: ["CAMPUS"],
    input: { POWER_TRANSFORMER: 220, SUPERCONDUCTOR: 25, COPPER_WIRE: 700 },
    output: { GRID_BACKBONE: 43 },
    power: 1_100,
    pollution: 2,
    crew: 300,
    buildCost: 20_000_000,
    baseValue: 38_000_000,
    cleanRoom: false,
    buff: { powerDiscount: 0.4 },
    blurb: "Superconducting trunk line carrying the load of a whole industrial belt.",
    sprite: "plant_transformer",
  },
  PHARMA_COMPLEX: {
    id: "PHARMA_COMPLEX",
    name: "Pharma complex",
    abbr: "PHARMA LINE",
    tier: 5,
    terrains: ["CAMPUS"],
    input: { SYNTHETIC_DRUG: 200, CHEMICAL_REACTOR: 20 },
    output: { PHARMA_LINE: 29 },
    power: 1_300,
    pollution: 3,
    crew: 310,
    buildCost: 19_000_000,
    baseValue: 36_000_000,
    cleanRoom: true,
    buff: { moraleLift: 2 },
    blurb: "Sterile filling, blistering and packaging. Margins nobody discusses in public.",
    sprite: "plant_pharma",
  },
  TRANSIT_WORKS: {
    id: "TRANSIT_WORKS",
    name: "Transit works",
    abbr: "TRANSIT",
    tier: 5,
    terrains: ["CAMPUS"],
    input: { HEAVY_HAULER: 120, SUPERCONDUCTOR: 20, SENSOR_ARRAY: 60 },
    output: { MAGLEV_TRAIN: 19 },
    power: 1_200,
    pollution: 1,
    crew: 330,
    buildCost: 22_000_000,
    baseValue: 42_000_000,
    cleanRoom: false,
    buff: { freightDiscount: 0.45, railDecayMultiplier: 0.5 },
    blurb: "Levitated stock that hauls tonnage across the board in a single window.",
    sprite: "plant_gigafactory",
  },
  COMPLEX_WORKS: {
    id: "COMPLEX_WORKS",
    name: "Complex works",
    abbr: "COMPLEX",
    tier: 5,
    terrains: ["CAMPUS"],
    input: { CHEMICAL_REACTOR: 130, POWER_TRANSFORMER: 100, STEEL_PLATE: 500 },
    output: { REFINERY_COMPLEX: 58 },
    power: 1_400,
    pollution: 4,
    crew: 320,
    buildCost: 17_000_000,
    baseValue: 32_000_000,
    cleanRoom: false,
    buff: { yieldByTier: { 2: 1.2, 3: 1.15 } },
    blurb: "A whole processing train in one shell, sized for a district instead of a plant.",
    sprite: "plant_complex",
  },
  ARCOLOGY_WORKS: {
    id: "ARCOLOGY_WORKS",
    name: "Arcology works",
    abbr: "ARCOLOGY",
    tier: 5,
    terrains: ["CAMPUS"],
    input: { COMPOSITE_PANEL: 700, FUEL_CELL: 90, MEDICAL_ISOTOPE: 15 },
    output: { ARCOLOGY: 24 },
    power: 1_600,
    pollution: 1,
    crew: 340,
    buildCost: 30_000_000,
    baseValue: 56_000_000,
    cleanRoom: false,
    buff: { moraleLift: 3, auditRelief: 0.1 },
    blurb: "Housing, works and shops under one roof. A company town with better plumbing.",
    sprite: "plant_arcology",
  },

  // Tier six. Crown goods, raised at the centre of the board.
  APEX_MEGAPROJECT: {
    id: "APEX_MEGAPROJECT",
    name: "Apex megaproject",
    abbr: "APEX",
    tier: 6,
    terrains: ["CROWN", "CAMPUS"],
    input: { COMPUTE_CLUSTER: 80, FUSION_REACTOR: 18, ORBITAL_NETWORK: 15 },
    output: { APEX_CORE: 7 },
    power: 11_000,
    pollution: 2,
    crew: 480,
    buildCost: 90_000_000,
    baseValue: 220_000_000,
    cleanRoom: false,
    buff: { blackoutRelief: 1, auditRelief: 0.15 },
    blurb: "The crown jewel. Whoever runs it skims five percent of every trade on the floor.",
    sprite: "plant_mega",
  },
  CONTINENTAL_GRID_WORKS: {
    id: "CONTINENTAL_GRID_WORKS",
    name: "Continental grid works",
    abbr: "CONTINENTAL",
    tier: 6,
    terrains: ["CROWN", "CAMPUS"],
    input: { GRID_BACKBONE: 80, FUSION_REACTOR: 12, MAGLEV_TRAIN: 10 },
    output: { CONTINENTAL_GRID: 6 },
    power: 12_000,
    pollution: 2,
    crew: 500,
    buildCost: 100_000_000,
    baseValue: 240_000_000,
    cleanRoom: false,
    buff: { powerDiscount: 0.6, tariffRebate: 0.5 },
    blurb: "One trunk line from the rim to the crown. Whoever owns it sets the tariff.",
    sprite: "plant_crown",
  },
  ELEVATOR_WORKS: {
    id: "ELEVATOR_WORKS",
    name: "Elevator works",
    abbr: "ELEVATOR",
    tier: 6,
    terrains: ["CROWN", "CAMPUS"],
    input: { ORBITAL_NETWORK: 70, AUTONOMOUS_FLEET: 25, COMPOSITE_PANEL: 1_400 },
    output: { ORBITAL_ELEVATOR: 4 },
    power: 13_000,
    pollution: 1,
    crew: 520,
    buildCost: 120_000_000,
    baseValue: 280_000_000,
    cleanRoom: false,
    buff: { freightDiscount: 0.6 },
    blurb: "A tether to the sky. Freight leaves the planet on your invoice.",
    sprite: "plant_crown",
  },
  DYNASTY_WORKS: {
    id: "DYNASTY_WORKS",
    name: "Dynasty works",
    abbr: "DYNASTY",
    tier: 6,
    terrains: ["CROWN", "CAMPUS"],
    input: { ARCOLOGY: 55, PHARMA_LINE: 40, REFINERY_COMPLEX: 30 },
    output: { DYNASTY_TRUST: 4 },
    power: 14_000,
    pollution: 3,
    crew: 560,
    buildCost: 140_000_000,
    baseValue: 320_000_000,
    cleanRoom: false,
    buff: { auditRelief: 0.3, moraleLift: 5 },
    blurb: "Pharma, housing and refining under one indenture that never expires.",
    sprite: "plant_crown",
  },
};

export const RECIPE_LIST: Recipe[] = Object.values(RECIPES).filter((r) => r.id !== "NONE");

export const TIER_ORDER: number[] = [1, 2, 3, 4, 5, 6];

export const RECIPES_BY_TIER: Record<number, Recipe[]> = Object.fromEntries(
  TIER_ORDER.map((tier) => [tier, RECIPE_LIST.filter((r) => r.tier === tier)]),
);

export const EXTRACTOR_RECIPES: Recipe[] = RECIPE_LIST.filter((r) => r.tier === 1);

/** Raw material to the one plant that pulls it out of the ground. */
export const DEPOSIT_RECIPE: Partial<Record<Resource, RecipeId>> = Object.fromEntries(
  EXTRACTOR_RECIPES.filter((r) => r.deposit).map((r) => [r.deposit as Resource, r.id]),
) as Partial<Record<Resource, RecipeId>>;

export const RECIPE_ABBR: Record<RecipeId, string> = Object.fromEntries(
  Object.values(RECIPES).map((r) => [r.id, r.abbr]),
) as Record<RecipeId, string>;

export function recipeOf(id: RecipeId): Recipe {
  return RECIPES[id];
}

/** What a plant is worth in goods per tick at reference prices. */
export function outputValueOf(
  recipe: Recipe,
  priceOf: (resource: Resource) => number,
): number {
  return (Object.entries(recipe.output) as [Resource, number][]).reduce(
    (sum, [resource, qty]) => sum + qty * priceOf(resource),
    0,
  );
}

export function inputValueOf(recipe: Recipe, priceOf: (resource: Resource) => number): number {
  return (Object.entries(recipe.input) as [Resource, number][]).reduce(
    (sum, [resource, qty]) => sum + qty * priceOf(resource),
    0,
  );
}
