import { RESOURCE_IDS, type CommodityFamily, type Resource } from "./ids";

export interface Commodity {
  id: Resource;
  name: string;
  abbr: string;
  family: CommodityFamily;
  /** Production tier. Zero for waste streams and for grid power. */
  tier: number;
  /** Reference price. Waste carries zero and costs money to hold instead. */
  basePrice: number;
  unit: string;
  /** One line, quoted by the exchange board, the inspector and the paper. */
  blurb: string;
  /** Sixteen by sixteen icon art key. */
  icon: string;
  /** Pixel tint applied to the icon and to every list swatch. */
  tint: string;
}

export const COMMODITIES: Record<Resource, Commodity> = {
  // Waste. Nobody buys it, everybody makes it, and it fouls the ground.
  TOXIC_SLAG: {
    id: "TOXIC_SLAG",
    name: "Toxic slag",
    abbr: "SLG",
    family: "WASTE",
    tier: 0,
    basePrice: 0,
    unit: "t",
    blurb: "Heavy metal residue that costs money to hold and poisons the plot it sits on.",
    icon: "icon_sack",
    tint: "#8a9a4a",
  },
  SPENT_ACID: {
    id: "SPENT_ACID",
    name: "Spent acid",
    abbr: "SAC",
    family: "WASTE",
    tier: 0,
    basePrice: 0,
    unit: "t",
    blurb: "Exhausted pickling liquor. Recovery plants buy it back, nothing else wants it.",
    icon: "icon_tank",
    tint: "#8a9a4a",
  },
  FLUE_ASH: {
    id: "FLUE_ASH",
    name: "Flue ash",
    abbr: "ASH",
    family: "WASTE",
    tier: 0,
    basePrice: 0,
    unit: "t",
    blurb: "Powder scraped out of the stacks. Cements into something if you work it.",
    icon: "icon_sack",
    tint: "#8a8479",
  },
  TAILINGS: {
    id: "TAILINGS",
    name: "Mill tailings",
    abbr: "TAL",
    family: "WASTE",
    tier: 0,
    basePrice: 0,
    unit: "t",
    blurb: "Wet sludge off the mill floor, still carrying traces of what was missed.",
    icon: "icon_tank",
    tint: "#6d6457",
  },
  POWER: {
    id: "POWER",
    name: "Grid power",
    abbr: "PWR",
    family: "UTILITY",
    tier: 0,
    basePrice: 60,
    unit: "MW",
    blurb: "Bought from the public grid at the board price, or generated under your own roof.",
    icon: "icon_bolt",
    tint: "#d99a1a",
  },

  // Raw. Ring five deposits.
  CRUDE_OIL: {
    id: "CRUDE_OIL",
    name: "Crude oil",
    abbr: "OIL",
    family: "RAW",
    tier: 1,
    basePrice: 90,
    unit: "bbl",
    blurb: "Sweet and sour alike. Everything plastic and everything burning starts here.",
    icon: "icon_barrel",
    tint: "#2f2a24",
  },
  BAUXITE: {
    id: "BAUXITE",
    name: "Bauxite",
    abbr: "BAU",
    family: "RAW",
    tier: 1,
    basePrice: 70,
    unit: "t",
    blurb: "Red dirt that turns into aluminium if you are willing to pay for the power.",
    icon: "icon_rock",
    tint: "#b06a4a",
  },
  SILICON_ORE: {
    id: "SILICON_ORE",
    name: "Silicon ore",
    abbr: "SIL",
    family: "RAW",
    tier: 1,
    basePrice: 120,
    unit: "t",
    blurb: "Quartz and sand by the quarry load. Bottles, glass and every wafer under them.",
    icon: "icon_sand",
    tint: "#9c9180",
  },
  LITHIUM: {
    id: "LITHIUM",
    name: "Lithium brine",
    abbr: "LIT",
    family: "RAW",
    tier: 1,
    basePrice: 260,
    unit: "t",
    blurb: "Pumped out of salt flats and left to evaporate in shallow pans.",
    icon: "icon_gem",
    tint: "#c9bda1",
  },
  COAL: {
    id: "COAL",
    name: "Coal",
    abbr: "COA",
    family: "RAW",
    tier: 1,
    basePrice: 40,
    unit: "t",
    blurb: "Cheap, filthy and still the backbone of every furnace on the board.",
    icon: "icon_rock",
    tint: "#2f2a24",
  },
  RARE_EARTH: {
    id: "RARE_EARTH",
    name: "Rare earth",
    abbr: "REE",
    family: "RAW",
    tier: 1,
    basePrice: 420,
    unit: "kg",
    blurb: "Seventeen metals that all behave alike, and all of them are needed at once.",
    icon: "icon_gem",
    tint: "#4a7a6a",
  },
  IRON_ORE: {
    id: "IRON_ORE",
    name: "Iron ore",
    abbr: "IRN",
    family: "RAW",
    tier: 1,
    basePrice: 55,
    unit: "t",
    blurb: "Rust coloured rock. Steel is the only story it has ever told.",
    icon: "icon_rock",
    tint: "#8c2f28",
  },
  COPPER_ORE: {
    id: "COPPER_ORE",
    name: "Copper ore",
    abbr: "COP",
    family: "RAW",
    tier: 1,
    basePrice: 150,
    unit: "t",
    blurb: "Green stained rock. Every wire, every coil and every contract runs through it.",
    icon: "icon_rock",
    tint: "#b06a4a",
  },
  SULFUR: {
    id: "SULFUR",
    name: "Sulfur",
    abbr: "SUL",
    family: "RAW",
    tier: 1,
    basePrice: 95,
    unit: "t",
    blurb: "Yellow cakes stacked to the horizon. Acid, fertiliser and a very bad smell.",
    icon: "icon_nugget",
    tint: "#c19a3a",
  },
  PHOSPHATE: {
    id: "PHOSPHATE",
    name: "Phosphate rock",
    abbr: "PHO",
    family: "RAW",
    tier: 1,
    basePrice: 85,
    unit: "t",
    blurb: "Strip mined and ground down. Crops grow on it and so does everything else.",
    icon: "icon_sand",
    tint: "#9c9180",
  },
  URANIUM: {
    id: "URANIUM",
    name: "Uranium ore",
    abbr: "URN",
    family: "RAW",
    tier: 1,
    basePrice: 640,
    unit: "kg",
    blurb: "A shaft, a respirator and a ledger nobody asks to see twice.",
    icon: "icon_gem",
    tint: "#4a7a6a",
  },
  TUNGSTEN_ORE: {
    id: "TUNGSTEN_ORE",
    name: "Tungsten ore",
    abbr: "TNG",
    family: "RAW",
    tier: 1,
    basePrice: 520,
    unit: "t",
    blurb: "The hardest thing anybody has dug up, and it will not melt for you either.",
    icon: "icon_gem",
    tint: "#8a8479",
  },
  GRAPHITE: {
    id: "GRAPHITE",
    name: "Natural graphite",
    abbr: "GRA",
    family: "RAW",
    tier: 1,
    basePrice: 180,
    unit: "t",
    blurb: "Soft black banks. Lubricates, conducts and lines every furnace lining.",
    icon: "icon_rock",
    tint: "#2f2a24",
  },
  TIMBER: {
    id: "TIMBER",
    name: "Timber",
    abbr: "TMB",
    family: "RAW",
    tier: 1,
    basePrice: 60,
    unit: "m3",
    blurb: "Felled faster than it grows. Pulp, sleepers and the ties under every span.",
    icon: "icon_log",
    tint: "#8f7a3f",
  },
  ROCK_SALT: {
    id: "ROCK_SALT",
    name: "Rock salt",
    abbr: "SLT",
    family: "RAW",
    tier: 1,
    basePrice: 45,
    unit: "t",
    blurb: "Halite off the pan. Chlorine, caustic and a road that stays open in winter.",
    icon: "icon_sand",
    tint: "#c9bda1",
  },

  // Refined. Ring four refineries.
  POLYMER: {
    id: "POLYMER",
    name: "Polymer",
    abbr: "POL",
    family: "REFINED",
    tier: 2,
    basePrice: 180,
    unit: "t",
    blurb: "Cracked and recombined oil. Pellets that become everything light and cheap.",
    icon: "icon_powder",
    tint: "#8a8479",
  },
  ALUMINUM: {
    id: "ALUMINUM",
    name: "Aluminium",
    abbr: "ALU",
    family: "REFINED",
    tier: 2,
    basePrice: 320,
    unit: "t",
    blurb: "Light, stubborn to make, and worth a small fortune in the power it drinks.",
    icon: "icon_ingot",
    tint: "#9c9180",
  },
  STEEL: {
    id: "STEEL",
    name: "Steel",
    abbr: "STL",
    family: "REFINED",
    tier: 2,
    basePrice: 240,
    unit: "t",
    blurb: "Poured by the ladle. Rails, girders, hulls and the roofs of company towns.",
    icon: "icon_ingot",
    tint: "#6d6457",
  },
  COPPER: {
    id: "COPPER",
    name: "Copper",
    abbr: "CUP",
    family: "REFINED",
    tier: 2,
    basePrice: 420,
    unit: "t",
    blurb: "Anodes off the smelter floor. The whole telegraph age hangs on the wire.",
    icon: "icon_ingot",
    tint: "#b06a4a",
  },
  SULFURIC_ACID: {
    id: "SULFURIC_ACID",
    name: "Sulfuric acid",
    abbr: "ACD",
    family: "REFINED",
    tier: 2,
    basePrice: 210,
    unit: "drums",
    blurb: "The workhorse reagent. Nothing refines without a drum of it on the dock.",
    icon: "icon_barrel",
    tint: "#c19a3a",
  },
  LITHIUM_CARBONATE: {
    id: "LITHIUM_CARBONATE",
    name: "Lithium carbonate",
    abbr: "LCO",
    family: "REFINED",
    tier: 2,
    basePrice: 690,
    unit: "t",
    blurb: "White powder out of the brine pans. Cells begin and end with it.",
    icon: "icon_powder",
    tint: "#c9bda1",
  },
  RARE_EARTH_OXIDE: {
    id: "RARE_EARTH_OXIDE",
    name: "Rare earth oxide",
    abbr: "REO",
    family: "REFINED",
    tier: 2,
    basePrice: 900,
    unit: "kg",
    blurb: "Separated at ruinous cost into magnets, catalysts and phosphors.",
    icon: "icon_powder",
    tint: "#4a7a6a",
  },
  SILICA: {
    id: "SILICA",
    name: "Refined silica",
    abbr: "SLC",
    family: "REFINED",
    tier: 2,
    basePrice: 260,
    unit: "t",
    blurb: "Kiln dried and graded. Glass, wafers and everything that must stay clean.",
    icon: "icon_sand",
    tint: "#ded4c3",
  },
  CEMENT: {
    id: "CEMENT",
    name: "Cement",
    abbr: "CEM",
    family: "REFINED",
    tier: 2,
    basePrice: 130,
    unit: "t",
    blurb: "Burned, ground and bagged. It sets the whole coastline in stone.",
    icon: "icon_sack",
    tint: "#8a8479",
  },
  FERTILIZER: {
    id: "FERTILIZER",
    name: "Fertilizer",
    abbr: "FRT",
    family: "REFINED",
    tier: 2,
    basePrice: 190,
    unit: "t",
    blurb: "Ammonia and phosphate blended for the hinterland. Bread is grown on it.",
    icon: "icon_sack",
    tint: "#8f7a3f",
  },
  PAPER_PULP: {
    id: "PAPER_PULP",
    name: "Paper pulp",
    abbr: "PLP",
    family: "REFINED",
    tier: 2,
    basePrice: 150,
    unit: "t",
    blurb: "Sodden rags and wood chips. Every share certificate passes through a pulp mill.",
    icon: "icon_log",
    tint: "#c9bda1",
  },
  URANIUM_OXIDE: {
    id: "URANIUM_OXIDE",
    name: "Uranium oxide",
    abbr: "UOX",
    family: "REFINED",
    tier: 2,
    basePrice: 1450,
    unit: "kg",
    blurb: "Yellowcake in sealed drums. The mill leaves tailings by the acre.",
    icon: "icon_barrel",
    tint: "#8a9a4a",
  },
  TUNGSTEN_CARBIDE: {
    id: "TUNGSTEN_CARBIDE",
    name: "Tungsten carbide",
    abbr: "TWC",
    family: "REFINED",
    tier: 2,
    basePrice: 1900,
    unit: "kg",
    blurb: "Pressed into cutters, dies and anything else that must not wear out.",
    icon: "icon_nugget",
    tint: "#6d6457",
  },
  SYNTHETIC_GRAPHITE: {
    id: "SYNTHETIC_GRAPHITE",
    name: "Synthetic graphite",
    abbr: "SGR",
    family: "REFINED",
    tier: 2,
    basePrice: 480,
    unit: "t",
    blurb: "Baked electrodes and anode stock, cleaner than anything dug up.",
    icon: "icon_rock",
    tint: "#3a322a",
  },
  FUEL_OIL: {
    id: "FUEL_OIL",
    name: "Fuel oil",
    abbr: "FOL",
    family: "REFINED",
    tier: 2,
    basePrice: 140,
    unit: "bbl",
    blurb: "The heavy cut. Burns under boilers, in turbines and in the worst engines made.",
    icon: "icon_barrel",
    tint: "#4d4237",
  },

  // Components. Ring three works.
  MICROCHIP: {
    id: "MICROCHIP",
    name: "Microchips",
    abbr: "CHP",
    family: "COMPONENT",
    tier: 3,
    basePrice: 900,
    unit: "units",
    blurb: "Dies off a clean room line. One speck of ash ruins a whole shift.",
    icon: "icon_circuit",
    tint: "#4a7a6a",
  },
  CIRCUIT_BOARD: {
    id: "CIRCUIT_BOARD",
    name: "Circuit boards",
    abbr: "PCB",
    family: "COMPONENT",
    tier: 3,
    basePrice: 1600,
    unit: "units",
    blurb: "Chips soldered onto laminate. The nervous system of every machine on the board.",
    icon: "icon_circuit",
    tint: "#8a9a4a",
  },
  BATTERY: {
    id: "BATTERY",
    name: "Lithium batteries",
    abbr: "BAT",
    family: "COMPONENT",
    tier: 3,
    basePrice: 1400,
    unit: "units",
    blurb: "Cells stacked into packs. Chemistry that will happily burn down a warehouse.",
    icon: "icon_cell",
    tint: "#4a7a6a",
  },
  COPPER_WIRE: {
    id: "COPPER_WIRE",
    name: "Copper wire",
    abbr: "CWR",
    family: "COMPONENT",
    tier: 3,
    basePrice: 780,
    unit: "km",
    blurb: "Drawn, annealed and insulated. The cheapest way to move power across a valley.",
    icon: "icon_spool",
    tint: "#b06a4a",
  },
  STEEL_PLATE: {
    id: "STEEL_PLATE",
    name: "Steel plate",
    abbr: "SPL",
    family: "COMPONENT",
    tier: 3,
    basePrice: 620,
    unit: "t",
    blurb: "Rolled flat and certified. Pressure vessels, hulls and armour.",
    icon: "icon_sheet",
    tint: "#6d6457",
  },
  GLASS_PANEL: {
    id: "GLASS_PANEL",
    name: "Glass panels",
    abbr: "GLP",
    family: "COMPONENT",
    tier: 3,
    basePrice: 540,
    unit: "units",
    blurb: "Float glass polished to a finish that shows every fingerprint on the floor.",
    icon: "icon_sheet",
    tint: "#9c9180",
  },
  MAGNET: {
    id: "MAGNET",
    name: "Rare earth magnets",
    abbr: "MGN",
    family: "COMPONENT",
    tier: 3,
    basePrice: 1250,
    unit: "units",
    blurb: "Sintered and plated. Small enough to pocket and strong enough to maim.",
    icon: "icon_magnet",
    tint: "#8a2f28",
  },
  TURBINE_BLADE: {
    id: "TURBINE_BLADE",
    name: "Turbine blades",
    abbr: "TBL",
    family: "COMPONENT",
    tier: 3,
    basePrice: 3400,
    unit: "units",
    blurb: "Cast, coated and balanced. They run red hot and never stop turning.",
    icon: "icon_gear",
    tint: "#9c9180",
  },
  COMPOSITE_PANEL: {
    id: "COMPOSITE_PANEL",
    name: "Composite panels",
    abbr: "CMP",
    family: "COMPONENT",
    tier: 3,
    basePrice: 2100,
    unit: "units",
    blurb: "Layered plastic and carbon. Half the weight of plate and twice the argument.",
    icon: "icon_sheet",
    tint: "#3a322a",
  },
  BEARING: {
    id: "BEARING",
    name: "Bearings",
    abbr: "BRG",
    family: "COMPONENT",
    tier: 3,
    basePrice: 1050,
    unit: "units",
    blurb: "Ground to a ten thousandth. Every machine in the world dies without them.",
    icon: "icon_gear",
    tint: "#6d6457",
  },
  REACTOR_FUEL: {
    id: "REACTOR_FUEL",
    name: "Reactor fuel",
    abbr: "RFL",
    family: "COMPONENT",
    tier: 3,
    basePrice: 6800,
    unit: "bundles",
    blurb: "Enriched, clad and counted twice. Guards on the gate and a ledger in a safe.",
    icon: "icon_reactor",
    tint: "#8a9a4a",
  },
  CATALYST: {
    id: "CATALYST",
    name: "Catalyst",
    abbr: "CTL",
    family: "COMPONENT",
    tier: 3,
    basePrice: 2400,
    unit: "kg",
    blurb: "Platinum on a ceramic honeycomb. It makes reactions go and does not get used up.",
    icon: "icon_catalyst",
    tint: "#c9bda1",
  },
  HYDRAULIC_UNIT: {
    id: "HYDRAULIC_UNIT",
    name: "Hydraulic units",
    abbr: "HYD",
    family: "COMPONENT",
    tier: 3,
    basePrice: 1850,
    unit: "units",
    blurb: "Pumps, rams and valves rated to move a mountain one stroke at a time.",
    icon: "icon_gear",
    tint: "#4a6b82",
  },
  PRECISION_OPTICS: {
    id: "PRECISION_OPTICS",
    name: "Precision optics",
    abbr: "POC",
    family: "COMPONENT",
    tier: 3,
    basePrice: 3100,
    unit: "units",
    blurb: "Ground and polished to fractions of a wavelength. Ash is the natural enemy.",
    icon: "icon_lens",
    tint: "#4a7a6a",
  },
  SOLVENT: {
    id: "SOLVENT",
    name: "Industrial solvent",
    abbr: "SLV",
    family: "COMPONENT",
    tier: 3,
    basePrice: 430,
    unit: "drums",
    blurb: "Distilled clean enough to wash a reactor, cheap enough to spill.",
    icon: "icon_barrel",
    tint: "#8a8479",
  },

  // Devices. Ring two advanced.
  NEURAL_CORE: {
    id: "NEURAL_CORE",
    name: "Neural cores",
    abbr: "NRL",
    family: "DEVICE",
    tier: 4,
    basePrice: 6000,
    unit: "units",
    blurb: "Silicon that learns. The lab claims it thinks and the market believes it.",
    icon: "icon_stack",
    tint: "#4a7a6a",
  },
  ROBOTIC_UNIT: {
    id: "ROBOTIC_UNIT",
    name: "Robotic units",
    abbr: "ROB",
    family: "DEVICE",
    tier: 4,
    basePrice: 3200,
    unit: "units",
    blurb: "Arms, frames and actuators. They do not join unions and they do not sleep.",
    icon: "icon_robot",
    tint: "#9c9180",
  },
  SATELLITE: {
    id: "SATELLITE",
    name: "Satellites",
    abbr: "SAT",
    family: "DEVICE",
    tier: 4,
    basePrice: 14000,
    unit: "units",
    blurb: "Pressed, folded and launched. Everything above four hundred miles is yours.",
    icon: "icon_dish",
    tint: "#4a6b82",
  },
  GAS_TURBINE: {
    id: "GAS_TURBINE",
    name: "Gas turbines",
    abbr: "GTR",
    family: "DEVICE",
    tier: 4,
    basePrice: 9500,
    unit: "units",
    blurb: "A jet engine bolted to a generator. Power where the grid refuses to go.",
    icon: "icon_gear",
    tint: "#b06a4a",
  },
  POWER_TRANSFORMER: {
    id: "POWER_TRANSFORMER",
    name: "Transformers",
    abbr: "PTR",
    family: "DEVICE",
    tier: 4,
    basePrice: 5400,
    unit: "units",
    blurb: "Copper and oil in a steel tank. Nothing moves without a step up or a step down.",
    icon: "icon_tower",
    tint: "#8f7a3f",
  },
  HEAVY_HAULER: {
    id: "HEAVY_HAULER",
    name: "Heavy haulers",
    abbr: "HVH",
    family: "DEVICE",
    tier: 4,
    basePrice: 7800,
    unit: "units",
    blurb: "Diesel trucks rated for the pit road. They will cross ground that rails cannot.",
    icon: "icon_truck",
    tint: "#a9542a",
  },
  CHEMICAL_REACTOR: {
    id: "CHEMICAL_REACTOR",
    name: "Chemical reactors",
    abbr: "CHR",
    family: "DEVICE",
    tier: 4,
    basePrice: 11500,
    unit: "units",
    blurb: "Jacketed vessels with agitation and relief. Chemistry at pressure and scale.",
    icon: "icon_reactor",
    tint: "#6d6457",
  },
  SENSOR_ARRAY: {
    id: "SENSOR_ARRAY",
    name: "Sensor arrays",
    abbr: "SNA",
    family: "DEVICE",
    tier: 4,
    basePrice: 4600,
    unit: "units",
    blurb: "Every gauge, every camera, every wire that reports to somebody far away.",
    icon: "icon_lens",
    tint: "#4a7a6a",
  },
  MEDICAL_ISOTOPE: {
    id: "MEDICAL_ISOTOPE",
    name: "Medical isotopes",
    abbr: "MIZ",
    family: "DEVICE",
    tier: 4,
    basePrice: 18000,
    unit: "vials",
    blurb: "Short lived and irreplaceable. The hospital pays whatever the invoice says.",
    icon: "icon_pill",
    tint: "#4a7a6a",
  },
  SYNTHETIC_DRUG: {
    id: "SYNTHETIC_DRUG",
    name: "Synthetic drugs",
    abbr: "SYD",
    family: "DEVICE",
    tier: 4,
    basePrice: 8900,
    unit: "cases",
    blurb: "Patented, branded and priced by what the market will bear without complaint.",
    icon: "icon_pill",
    tint: "#a9542a",
  },
  FUEL_CELL: {
    id: "FUEL_CELL",
    name: "Fuel cells",
    abbr: "FCL",
    family: "DEVICE",
    tier: 4,
    basePrice: 12400,
    unit: "units",
    blurb: "Hydrogen in, power out, water as the only exhaust. Costly and quiet.",
    icon: "icon_cell",
    tint: "#4a6b82",
  },
  SUPERCONDUCTOR: {
    id: "SUPERCONDUCTOR",
    name: "Superconductors",
    abbr: "SCD",
    family: "DEVICE",
    tier: 4,
    basePrice: 21000,
    unit: "km",
    blurb: "Wire that carries current with no losses, if you keep it cold enough.",
    icon: "icon_spool",
    tint: "#4a7a6a",
  },

  // Systems. Ring one campus.
  COMPUTE_CLUSTER: {
    id: "COMPUTE_CLUSTER",
    name: "Compute clusters",
    abbr: "CCL",
    family: "SYSTEM",
    tier: 5,
    basePrice: 48000,
    unit: "halls",
    blurb: "Neural cores in racks with the cooling to match. A mill for thinking.",
    icon: "icon_stack",
    tint: "#4a7a6a",
  },
  AUTONOMOUS_FLEET: {
    id: "AUTONOMOUS_FLEET",
    name: "Autonomous fleets",
    abbr: "AUF",
    family: "SYSTEM",
    tier: 5,
    basePrice: 62000,
    unit: "fleets",
    blurb: "Driverless haulage running the pit road around the clock and never tiring.",
    icon: "icon_truck",
    tint: "#4a6b82",
  },
  ORBITAL_NETWORK: {
    id: "ORBITAL_NETWORK",
    name: "Orbital networks",
    abbr: "ORB",
    family: "SYSTEM",
    tier: 5,
    basePrice: 88000,
    unit: "networks",
    blurb: "Constellations enough to cover every acre of the board at once.",
    icon: "icon_dish",
    tint: "#4a6b82",
  },
  FUSION_REACTOR: {
    id: "FUSION_REACTOR",
    name: "Fusion reactors",
    abbr: "FSN",
    family: "SYSTEM",
    tier: 5,
    basePrice: 145000,
    unit: "reactors",
    blurb: "A star in a bottle, if the bottle holds. Every rival wants the drawings.",
    icon: "icon_reactor",
    tint: "#d99a1a",
  },
  GRID_BACKBONE: {
    id: "GRID_BACKBONE",
    name: "Grid backbone",
    abbr: "GRB",
    family: "SYSTEM",
    tier: 5,
    basePrice: 74000,
    unit: "trunks",
    blurb: "Superconducting trunk line carrying the load of a whole industrial belt.",
    icon: "icon_tower",
    tint: "#c19a3a",
  },
  PHARMA_LINE: {
    id: "PHARMA_LINE",
    name: "Pharma lines",
    abbr: "PHL",
    family: "SYSTEM",
    tier: 5,
    basePrice: 96000,
    unit: "lines",
    blurb: "Sterile filling, blistering and packaging. Margins nobody discusses in public.",
    icon: "icon_pill",
    tint: "#4a7a6a",
  },
  MAGLEV_TRAIN: {
    id: "MAGLEV_TRAIN",
    name: "Maglev trains",
    abbr: "MGT",
    family: "SYSTEM",
    tier: 5,
    basePrice: 121000,
    unit: "trains",
    blurb: "Levitated stock that hauls tonnage across the board in a single window.",
    icon: "icon_train",
    tint: "#9c9180",
  },
  REFINERY_COMPLEX: {
    id: "REFINERY_COMPLEX",
    name: "Refinery complexes",
    abbr: "RFC",
    family: "SYSTEM",
    tier: 5,
    basePrice: 57000,
    unit: "complexes",
    blurb: "A whole processing train in one shell, sized for a district instead of a plant.",
    icon: "icon_plant",
    tint: "#8f7a3f",
  },
  ARCOLOGY: {
    id: "ARCOLOGY",
    name: "Arcologies",
    abbr: "ARC",
    family: "SYSTEM",
    tier: 5,
    basePrice: 168000,
    unit: "arcologies",
    blurb: "Housing, works and shops under one roof. Company town with better plumbing.",
    icon: "icon_plant",
    tint: "#6b7a8a",
  },

  // Crown goods. The centre of the board.
  APEX_CORE: {
    id: "APEX_CORE",
    name: "Apex cores",
    abbr: "APX",
    family: "CROWN",
    tier: 6,
    basePrice: 1600000,
    unit: "cores",
    blurb: "The finished megaproject. It skims five percent of everything traded on the floor.",
    icon: "icon_stack",
    tint: "#c19a3a",
  },
  CONTINENTAL_GRID: {
    id: "CONTINENTAL_GRID",
    name: "Continental grid",
    abbr: "CTG",
    family: "CROWN",
    tier: 6,
    basePrice: 2200000,
    unit: "grids",
    blurb: "One trunk line from the rim to the crown. Whoever owns it sets the tariff.",
    icon: "icon_tower",
    tint: "#d99a1a",
  },
  ORBITAL_ELEVATOR: {
    id: "ORBITAL_ELEVATOR",
    name: "Orbital elevator",
    abbr: "OEL",
    family: "CROWN",
    tier: 6,
    basePrice: 3600000,
    unit: "elevators",
    blurb: "A tether to the sky. Freight leaves the planet on your invoice.",
    icon: "icon_dish",
    tint: "#4a6b82",
  },
  DYNASTY_TRUST: {
    id: "DYNASTY_TRUST",
    name: "Dynasty trust",
    abbr: "DYT",
    family: "CROWN",
    tier: 6,
    basePrice: 5000000,
    unit: "trusts",
    blurb: "Pharma, housing and refining under a single indenture that never expires.",
    icon: "icon_vault",
    tint: "#c9bda1",
  },
};

export const ALL_RESOURCES: Resource[] = [...RESOURCE_IDS];

export const WASTE_RESOURCES: Resource[] = ALL_RESOURCES.filter(
  (id) => COMMODITIES[id].family === "WASTE",
);

/** Everything with a market row. Waste has no order book, only a disposal bill. */
export const TRADEABLE: Resource[] = ALL_RESOURCES.filter(
  (id) => COMMODITIES[id].family !== "WASTE",
);

export const EXTRACTED: Resource[] = ALL_RESOURCES.filter(
  (id) => COMMODITIES[id].family === "RAW",
);

export function commoditiesOfFamily(family: CommodityFamily): Resource[] {
  return ALL_RESOURCES.filter((id) => COMMODITIES[id].family === family);
}

export const FAMILY_LABEL: Record<CommodityFamily, string> = {
  RAW: "Raw material",
  REFINED: "Refined",
  COMPONENT: "Component",
  DEVICE: "Device",
  SYSTEM: "System",
  CROWN: "Crown good",
  WASTE: "Waste",
  UTILITY: "Utility",
};

export const FAMILY_ORDER: CommodityFamily[] = [
  "RAW",
  "REFINED",
  "COMPONENT",
  "DEVICE",
  "SYSTEM",
  "CROWN",
  "UTILITY",
  "WASTE",
];

export const RESOURCE_LABEL: Record<Resource, string> = Object.fromEntries(
  ALL_RESOURCES.map((id) => [id, COMMODITIES[id].name]),
) as Record<Resource, string>;

export const RESOURCE_ABBR: Record<Resource, string> = Object.fromEntries(
  ALL_RESOURCES.map((id) => [id, COMMODITIES[id].abbr]),
) as Record<Resource, string>;

export const BASE_PRICES: Record<Resource, number> = Object.fromEntries(
  ALL_RESOURCES.map((id) => [id, COMMODITIES[id].basePrice]),
) as Record<Resource, number>;

export const RESOURCE_ICON: Record<Resource, string> = Object.fromEntries(
  ALL_RESOURCES.map((id) => [id, COMMODITIES[id].icon]),
) as Record<Resource, string>;

export const RESOURCE_TINT: Record<Resource, string> = Object.fromEntries(
  ALL_RESOURCES.map((id) => [id, COMMODITIES[id].tint]),
) as Record<Resource, string>;

export function commodityOf(id: Resource): Commodity {
  return COMMODITIES[id];
}
